### PR TITLE
#52 Memoize start callback in useAnimation hook

### LINKED ISSUE #52: play value from useAnimate cannot be use in useEffect
**Describe the bug**
Value of `play` is changing during the animation and it cannot be used inside `useEffect`

**To Reproduce**
I want to play animation depends on `isOpened` prop from parent and I need value of `isPlaying` to conditionally show `children` (I think that is not doable using Animation component)
```js

const { play, style, isPlaying } = useAnimate({
  start: { opacity: 0 },
  end: { opacity: 1 },
  play: isOpened,
});

useEffect(() => {
  play(isOpened)
}, [isOpened, play]);

return (isOpened || isPlaying) ? children : null;
```

Above code produces infinite loop inside useEffect.

### PR DESCRIPTION
**Pull request by marcin-piela**
Closes #52

### CODE REVIEW

File: src/useAnimate.ts [hunk 1]
```diff
@@ -32,22 +35,26 @@ export default function useAnimate(
...
-    });
+  const play = React.useCallback(
+    (isPlay: boolean) => {
+      setStyle({
+        ...(isPlay ? end : start),
+        transition,
+      });
 
-    setIsPlaying(isPlay);
+      setIsPlaying(true);
```
Comment (bluebill1049) [inline src/useAnimate.ts]: Thanks for the PR :) why it’s always true here?

File: src/useAnimate.ts [hunk 2]
```diff
@@ -20,7 +20,10 @@ export default function useAnimate(
     duration = 0.3,
     easeType = 'linear',
   } = props;
-  const transition = `all ${duration}s ${easeType} ${delay}s`;
+  const transition = React.useMemo(
```
Comment (bluebill1049) [inline src/useAnimate.ts]: Nice

File: src/useAnimate.ts (hunk 1 above)
Comment (marcin-piela) [reply src/useAnimate.ts]: Cause even if we do `play(false)` animation starts and ends after Timeout

Comment (marcin-piela) [reply src/useAnimate.ts]: And I've added `setIsPlaying(false);` in timeout callback

Comment (marcin-piela) [reply src/useAnimate.ts]: But yeah.... something is still wrong here (some conditions need to be changed) :)

Comment (bluebill1049) [reply src/useAnimate.ts]: hmmm this may break the usage, i will investigate it bit more. Thanks tho :)

File: src/useAnimate.ts (hunk 2 above)
Comment (marcin-piela) [reply src/useAnimate.ts]: I've updated PR (moved one condition to setTimeout), I thought that `isPlaying` should inform whether animation is ended or not (with that approach we can easily unmount component when animation finished like in react-transition-group)

**Comment by bluebill1049** [comment]
hey @marcin-piela tried your code, I think this doesn't solve the issue https://codesandbox.io/s/blissful-fog-76c4g

**Comment by marcin-piela** [comment]
I think that it does, cause you have to use React.useMemo (or declare it above component) for `start` and `end`:
```js
const start = React.useMemo(() => ({ opacity: 0 }), []);
const end = React.useMemo(() => ({ opacity: 1 }), []);

const { play, style, isPlaying } = useAnimate({
    start: start,
    end: end,
    play: false,
    delay: 1
  });
```

otherwise `start` and `end` objects are created in every render (so they are different and hook useAnimation works as expected)

**Comment by bluebill1049** [comment]
what about this approach @marcin-piela : https://codesandbox.io/s/lucid-lamport-rc8lt

File: src/useAnimate.ts (hunk 2 above)
Comment (bluebill1049) [reply src/useAnimate.ts]: actually, I looked this again, this react `usememo` doesn't add too much performance value here.

Comment (marcin-piela) [reply src/useAnimate.ts]: It depends, for simple animation its about 3 calls per one `play`, but when you ie. change other props after first render it will be more and more

**Comment by marcin-piela** [comment]
> what about this approach @marcin-piela : https://codesandbox.io/s/lucid-lamport-rc8lt
> 
> I have used useRef in this example, looks like it's working for me, any thoughts?

I prefer to use `useCallback` but yes useRef will solve all issues without memoizing start and end styles, I've updated my PR

**Comment by bluebill1049** [comment]
thank you very much @marcin-piela
